### ISSUE TITLE
Fallback to stdout report for forks

### ISSUE THREAD

**Issue by ordian** [actions-rs/audit-check#104]
Please implement the same workaround for `audit-check` as [you did for clippy](https://github.com/actions-rs/clippy-check/commit/8bca5ed54edf5fd11b4288745f4ddfd7bd0de3f7).

**Comment by ordian** [comment]
I think it's mostly implemented and lacking a `return` statement for else branch here https://github.com/actions-rs/audit-check/blob/69fdbe9b61b75ba374c275c34559b56a8b9c643d/src/reporter.ts#L152-L156
@svartalf could you confirm?

**Comment by svartalf** [comment]
I would expect it to work already, just a line above from your snippet:

https://github.com/actions-rs/audit-check/blob/69fdbe9b61b75ba374c275c34559b56a8b9c643d/src/reporter.ts#L151

Do you have an example where it does not work as expected?

**Comment by ordian** [comment]
https://github.com/openethereum/openethereum/runs/562748013

**Comment by ordian** [comment]
It uses audit-check@v1
https://github.com/openethereum/openethereum/blob/master/.github/workflows/audit.yml

**Comment by ordian** [comment]
(This issue is about exiting successfully if in a fork with no errors)

**Comment by ordian** [comment]
I've noticed your branch https://github.com/actions-rs/audit-check/tree/issue-104, are there any updates?

**Comment by svartalf** [comment]
@ordian yeah, I'm working on it.
