### ISSUE TITLE
Action is not executed

### ISSUE THREAD

**Issue by vbrandl** [actions-rs/audit-check#30]
I created a [new branch in a Rust repository](https://github.com/editorconfig-checker/editorconfig-checker.rust/tree/feature/ci-audit/), added the [audit workflow](https://github.com/editorconfig-checker/editorconfig-checker.rust/blob/feature/ci-audit/.github/workflows/cargo-audit.yml) and pushed [a commit](https://github.com/editorconfig-checker/editorconfig-checker.rust/commit/a94268bb883a561d286839a1b896c0e5106e09f8), that changed both `Cargo.toml` and `Cargo.lock` to the same branch.

Somehow the action is still not executed: https://github.com/editorconfig-checker/editorconfig-checker.rust/actions

Is there anything else to do, for this action to work?

Update:

I added `on: pull_request:` to the action, and the action was executed when I created a PR for my branch. Is the `push` trigger only triggered on specific branches?

Update2:

The scheduled trigger is not executed, too. Same here: does the trigger only apply if the `yml` is on a specific branch?

**Comment by stevepentland** [comment]
@vbrandl with some experimentation I found that the path filters would not execute with the ** prefix even though the GH documentation says they should. 

When I changed:
```
  - '**/Cargo.toml'
  - '**/Cargo.lock'
```
to
```
  - 'Cargo.toml'
  - 'Cargo.lock'
```
The action executed as I expected

**Comment by svartalf** [comment]
Sorry for not getting into this earlier.

@vbrandl I do recall that scheduled Actions will be executed only when they are defined in the default repo branch (which is `master` usually), can you try that?

@stevepentland, it seems like it is worth to file an issue for this behavior for a GitHub, as it seems kinda unreasonable.

**Comment by vbrandl** [comment]
Thank you. Now it is working.

I have to investigate if in a repository with a cargo workspace and therefore multiple `Cargo.toml` files, the pattern still matches all `Cargo.toml` in the repository
