### ISSUE TITLE
Audit checks failing with `Cannot use 'in' operator to search for 'unmaintained' in yanked`

### ISSUE THREAD

**Issue by Licenser** [actions-rs/audit-check#84]
Hi,
I'm having an issue with the audit failing with the error:

```
Cannot use 'in' operator to search for 'unmaintained' in yanked
```

the related run is here:

https://github.com/wayfair-tremor/tremor-runtime/actions/runs/43254102

**Comment by svartalf** [comment]
I believe this bug was fixed in 35b7b53b1e25b55642157ac01b4adceb5b9ebef3, which was just released as `v1.2.0` version. If it is still reproducible, re-open this issue, please.
