### ISSUE TITLE
Instructions for generating `GITHUB_TOKEN`

### ISSUE THREAD

**Issue by azriel91** [actions-rs/audit-check#95]
Hiya, I can't find instructions on setting up the `GITHUB_TOKEN` -- ctrl F / searched issues / PRs. I'm assuming I would have to create a [personal access token](https://github.com/settings/tokens/new)

Based on [reporter.ts](https://github.com/actions-rs/audit-check/blob/master/src/reporter.ts), it's used for:

* `client.search.issuesAndPullRequests`
* `client.issues.create`
* `checks.CheckReporter(client, 'Security audit');`

Do those correspond to the **write/read:discussion**, and **workflow** permissions?
Is anything else missing?

**Comment by svartalf** [comment]
`GITHUB_TOKEN` is provided for you by GitHub itself, there is no need to create it manually.
I added a link to its documentation in 5fabacafcf45643692f4f6589c19a9278a66ec10, that should be more clear now.

**Comment by azriel91** [comment]
Sweet thanks!
